//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eshop.WpfMvvmApp.ControllerClients {
    
    
    public class BasketControllerClient : CoreWebApiClient.BaseApiControllerClient, IBasketControllerClient {
        
        public BasketControllerClient(string serverUrl, System.Web.Routing.RouteCollection routes) : 
                base(serverUrl, routes) {
        }
        
        public BasketControllerClient(string serverUrl, System.Web.Routing.RouteCollection routes, CoreWebApiClient.IAuthenticationCookiePersister authenticationCookiePersister) : 
                base(serverUrl, routes, authenticationCookiePersister) {
        }
        
        public virtual void AddProductToBasket(int productId, int quantity) {
            System.Web.Routing.RouteValueDictionary routeValues = new System.Web.Routing.RouteValueDictionary();
            routeValues.Add("quantity", quantity);
            this.HttpClientPost("AddProductToBasket", productId, routeValues);
        }
        
        public virtual System.Threading.Tasks.Task AddProductToBasketAsync(int productId, int quantity) {
            System.Web.Routing.RouteValueDictionary routeValues = new System.Web.Routing.RouteValueDictionary();
            routeValues.Add("quantity", quantity);
            return this.HttpClientPostAsync("AddProductToBasket", productId, routeValues);
        }
        
        public virtual Eshop.Dtos.BasketItemDto[] GetBasketItems() {
            System.Web.Routing.RouteValueDictionary routeValues = new System.Web.Routing.RouteValueDictionary();
            return this.HttpClientGet<Eshop.Dtos.BasketItemDto[]>("GetBasketItems", routeValues);
        }
        
        public virtual System.Threading.Tasks.Task<Eshop.Dtos.BasketItemDto[]> GetBasketItemsAsync() {
            System.Web.Routing.RouteValueDictionary routeValues = new System.Web.Routing.RouteValueDictionary();
            return this.HttpClientGetAsync<Eshop.Dtos.BasketItemDto[]>("GetBasketItems", routeValues);
        }
        
        public virtual void UpdateProductQuantity(int productId, int quantity) {
            System.Web.Routing.RouteValueDictionary routeValues = new System.Web.Routing.RouteValueDictionary();
            routeValues.Add("quantity", quantity);
            this.HttpClientPost("UpdateProductQuantity", productId, routeValues);
        }
        
        public virtual System.Threading.Tasks.Task UpdateProductQuantityAsync(int productId, int quantity) {
            System.Web.Routing.RouteValueDictionary routeValues = new System.Web.Routing.RouteValueDictionary();
            routeValues.Add("quantity", quantity);
            return this.HttpClientPostAsync("UpdateProductQuantity", productId, routeValues);
        }
    }
}
