//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eshop.WpfMvvmApp.ControllerClients {
    
    
    public interface IOrderControllerClient {
        
        void PlaceOrder(object notUsed);
        
        System.Threading.Tasks.Task PlaceOrderAsync(object notUsed);
    }
}
