//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eshop.WpfMvvmApp.ControllerClients {
    
    
    public interface IProductControllerClient {
        
        Eshop.Dtos.ProductSummaryDto[] SearchProducts(string searchedText);
        
        System.Threading.Tasks.Task<Eshop.Dtos.ProductSummaryDto[]> SearchProductsAsync(string searchedText);
        
        Eshop.Dtos.ProductDto GetProduct(int productId);
        
        System.Threading.Tasks.Task<Eshop.Dtos.ProductDto> GetProductAsync(int productId);
    }
}
