//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eshop.WpfMvvmApp.ControllerClients {
    
    
    public interface IDeliveryAddressControllerClient {
        
        void SetDeliveryAddress(string deliveryAddress);
        
        System.Threading.Tasks.Task SetDeliveryAddressAsync(string deliveryAddress);
        
        string GetDeliveryAddress();
        
        System.Threading.Tasks.Task<string> GetDeliveryAddressAsync();
    }
}
