//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eshop.WpfMvvmApp.ControllerClients {
    
    
    public interface IProductControllerClient {
        
        System.Collections.Generic.IEnumerable<Eshop.Dtos.ProductSummaryDto> Get(string searchText);
        
        System.Threading.Tasks.Task<System.Collections.Generic.IEnumerable<Eshop.Dtos.ProductSummaryDto>> GetAsync(string searchText);
        
        Eshop.Dtos.ProductDto Get(int productId);
        
        System.Threading.Tasks.Task<Eshop.Dtos.ProductDto> GetAsync(int productId);
        
        void AddProductToBasket(int productId, int quantity);
        
        System.Threading.Tasks.Task AddProductToBasketAsync(int productId, int quantity);
    }
}
